name: server-action.yml
on:
  push:
    branches: [ "main" ]
  schedule: [cron: "* * * * 6"]

jobs:
  APT-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Update & Upgrade
        run: sudo apt-get update && sudo apt-get upgrade

      - name: Rust install
        run: rustup install stable

  Cache-cleaner:
    runs-on: ubuntu-latest
    needs: [APT-Update]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Clear
        run: cargo cache --clear

  Build:
    runs-on: ubuntu-latest
    needs: [Cache-cleaner]
    steps:
      - name: Cargo Check
        run: cargo check

      - name: Cargo Build
        run: cargo build --release